version: '3.8'

services:
  nodejs_app:
    build: .
    container_name: nodejs_app
    restart: always
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs_app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

